services:
  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teste_db
    ports:
      - '5432:5432'
    networks:
      - app-network
    # volumes:
    #   - ./banco:/var/lib/postgresql/data

  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: teste_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - '8080:8081'
    depends_on:
      - db
    networks:
      - app-network
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

